# Generated by Django 3.0.4 on 2020-03-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joker',
            old_name='name',
            new_name='fname',
        ),
    ]
