# Generated by Django 3.0.4 on 2020-03-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0002_auto_20200306_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joker',
            old_name='fname',
            new_name='name',
        ),
    ]
